function [A,B,K] = simple_linear_model(r, x, dx)

%We use environement(1400, 40, 86000, rocket) as constant
Earth_M = 5.9724e+24; % e.Earth_M;
h_g = 1400; % e.h_g;
G = 6.6741e-11; % e.G;
Earth_R = 6378000; % e.Earth_R;
rho_g = 1.2250; % e.rho_g;
Temp_grad = 0.0065; % e.Temp_grad;
Temp_g = 313.1500; % e.Temp_g;
R = 287; %e.R;

%From the rocket
A_ref = r.A_ref;
Mass_dry = r.Mass_dry;
CS_Length = r.CS_Length;
CS_Angle = r.CS_Angle;
CS_Position = r.CS_Position;
CS_Area = r.CS_Area;
CS_CD0 = r.CS_CD0;
Xdot = r.Xdot;
u = r.u0;

dFdz = 2.*Earth_M.*G.*h_g.*(Earth_R+h_g.*x(1)).^(-3)+(-1/2).*A_ref.*Mass_dry.^(-1) ...
  .*rho_g.*x(2).^2.*(Temp_g.^(-1).*(Temp_g+(-1).*Temp_grad.*x(1))).^((-1)+ ...
  Earth_M.*G.*R.^(-1).*Temp_grad.^(-1).*(Earth_R+h_g.*x(1)).^(-2)).*((-1).* ...
  Temp_grad.*(Temp_g+(-1).*Temp_grad.*x(1)).^(-1).*((-1)+Earth_M.*G.*R.^( ...
  -1).*Temp_grad.^(-1).*(Earth_R+h_g.*x(1)).^(-2))+(-2).*Earth_M.*G.*h_g.* ...
  R.^(-1).*Temp_grad.^(-1).*(Earth_R+h_g.*x(1)).^(-3).*log(Temp_g.^(-1).*( ...
  Temp_g+(-1).*Temp_grad.*x(1)))).*(Cd_mandell_simple(Xdot)+3.*A_ref.^(-1).*CS_Area.* ...
  CS_CD0.*u.*(1+(-0.557171E-2).*CS_Length.^(-1).*CS_Position.*( ...
  CS_Position.*x(2)).^(-0.25E0).*csc(CS_Angle)).*sin(CS_Angle).^3);

dFdv = (-0.208939E-2).*CS_Area.*CS_CD0.*CS_Length.^(-1).*CS_Position.^2.* ...
  Mass_dry.^(-1).*rho_g.*u.*x(2).^2.*(CS_Position.*x(2)).^(-0.125E1).*( ...
  Temp_g.^(-1).*(Temp_g+(-1).*Temp_grad.*x(1))).^((-1)+Earth_M.*G.*R.^(-1) ...
  .*Temp_grad.^(-1).*(Earth_R+h_g.*x(1)).^(-2)).*sin(CS_Angle).^2+(-1).* ...
  A_ref.*Mass_dry.^(-1).*rho_g.*x(2).*(Temp_g.^(-1).*(Temp_g+(-1).* ...
  Temp_grad.*x(1))).^((-1)+Earth_M.*G.*R.^(-1).*Temp_grad.^(-1).*(Earth_R+ ...
  h_g.*x(1)).^(-2)).*(Cd_mandell_simple(Xdot)+3.*A_ref.^(-1).*CS_Area.*CS_CD0.*u.*(1+( ...
  -0.557171E-2).*CS_Length.^(-1).*CS_Position.*(CS_Position.*x(2)).^( ...
  -0.25E0).*csc(CS_Angle)).*sin(CS_Angle).^3);

dFdu = (-3/2).*CS_Area.*CS_CD0.*Mass_dry.^(-1).*rho_g.*x(2).^2.*(Temp_g.^(-1).*( ...
  Temp_g+(-1).*Temp_grad.*x(1))).^((-1)+Earth_M.*G.*R.^(-1).*Temp_grad.^( ...
  -1).*(Earth_R+h_g.*x(1)).^(-2)).*(1+(-0.557171E-2).*CS_Length.^(-1).* ...
  CS_Position.*(CS_Position.*x(2)).^(-0.25E0).*csc(CS_Angle)).*sin( ...
  CS_Angle).^3;

if imag(dFdz)+imag(dFdv)+imag(dFdu) ~= 0
    disp('warning: imaginary part in A or B matrix')
end
dFdz = real(dFdz);
dFdv = real(dFdv);
dFdu = real(dFdu);

A = [0 1; dFdz dFdv];
B = [0; dFdu];
K = dx-A*x-B*u;

end